### ISSUE TITLE
Install with composer errors out

### ISSUE THREAD

**Issue by ilessing** [scriptotek/php-sru-client#3]
Now I'm trying to install with composer and this time I get error message:
**[InvalidArgumentException]                                                                                                                                 
  Could not find package scriptotek/php-sru-client at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability** 

Here is transcript of install attempt.  Directory is clean before attempt.
```
webroot> composer require scriptotek/php-sru-client

                                                                                                                                                             
  [InvalidArgumentException]                                                                                                                                 
  Could not find package scriptotek/php-sru-client at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability  
                                                                                                                                                             

  require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

webroot> 
```

I don't know about how to set my minimum-stability if that is even the issue.

**Comment by ilessing** [comment]
I was able to install by downloading the composer.json file to my webroot/
Then I issued command:
`composer install`
and composer then created:

- `composer.lock` file
- a `vendor/` dir 
- 21 dirs in `vendor/`
- `vendor/autoload.php` file

**Comment by danmichaelo** [comment]
Here's a better way:

[![asciicast](https://asciinema.org/a/1cun7xsdyyjzqlizu0qply8a1.png)](https://asciinema.org/a/1cun7xsdyyjzqlizu0qply8a1)

**Comment by ilessing** [comment]
Thanks Dan!  That helps a lot.   Sometimes a screencast is just the thing to demonstrate a technique.

**Comment by S1SYPHOS** [comment]
Doesn't work that way anymore, I'm afraid:

```
Using version ^0.6.4 for scriptotek/sru-client
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for scriptotek/sru-client ^0.6.4 -> satisfiable by scriptotek/sru-client[v0.6.4].
    - scriptotek/sru-client v0.6.4 requires php-http/client-implementation ^1.0 -> no matching package found.
```

**Comment by danmichaelo** [comment]
@S1SYPHOS : Starting from sru-client version 0.6 you also need to install a HTTP client implementation. And from version 0.7 (released just now) you also need a HTTP factory implementation.

The following command installs everything you need:

```
composer require scriptotek/sru-client php-http/guzzle6-adapter http-interop/http-factory-guzzle
```

The reason for this is to support the new PSR-17 and PSR-18 standards.

**Comment by danmichaelo** [comment]
I also did a new screencast on how to install with `composer init` with version 0.7:

[![asciicast](https://asciinema.org/a/DOXWTjtaHzk1893f2TB0rYVez.svg)](https://asciinema.org/a/DOXWTjtaHzk1893f2TB0rYVez)
